# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
# this fails now because the repo is private
shallow_clone: false

os: Visual Studio 2017

platform: x64

# No need to run CI on the branch if we're also running CI for a PR.
skip_branch_with_pr: true

nuget:
  disable_publish_on_pr: true

init:
  ## Set environment variables.
  - ps: $env:JAVA_HOME = "C:\Program Files\Java\jdk1.8.0"
  - ps: $env:JAVA_HOME
  # Used by FindAnt.cmake:
  - ps: $env:ANT_HOME = "C:\Program Files\NetBeans 8.2\extide\ant"
  - ps: $env:OPENSIM_HOME = "C:/OpenSim"
  # Java must be on the PATH for Ant to find (Ant is run through CMake).
  - ps: $env:PATH = "$env:JAVA_HOME/bin;$env:OPENSIM_HOME/bin;$env:PATH"
  - ps: $env:PATH
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  #- ps: choco install jdk8 # We no longer get NetBeans through choco; this means we can use AppVeyor's provided JDK.

  ## The GUI is built with the Netbeans platform.
  # We need 8.2 and this isn't available on Chocolatey.
  #- ps: choco install netbeans-jee --version 8.1 --yes --limit-output --allow-empty-checksums| Out-Null
  # https://netbeans.org/downloads/start.html?platform=windows&lang=en&option=javase
  - appveyor DownloadFile http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javase-windows.exe
  # Make sure the NetBeans installer is not corrupted.
  - ps: $expectedHash = "7b0646306a7488e617837da1517a86c08b7cf6fbe4dd9d74e8a4564b5ffde004".ToUpper()
  - ps: $hashFromFile = Get-FileHash -Algorithm SHA256 -Path .\netbeans-8.2-javase-windows.exe
  - ps: if (($hashFromFile.Hash) -ne ($expectedHash)) { Write-Error "Hash doesn't match." }
  # Install NetBeans
  - ps: .\netbeans-8.2-javase-windows.exe --silent | Out-Null # This installer is gregaroius.
  
  ## Apache Ant for building Java projects.
  #- choco install ant --yes --limit-output # Provided by NetBeans.
  
  ## OpenSim (and Simbody).
  # OpenSim's installation is pushed to our Appveyor NuGet account feed.
  # http://help.appveyor.com/discussions/problems/6024-build-stalled-prompting-for-nuget-permissions#comment_41867748
  - nuget sources add -name opensim-core -source https://ci.appveyor.com/nuget/opensim-core-kd63opes1em0
  - nuget install opensim-core-VC141 -Version 0.0.0 -ExcludeVersion -OutputDirectory C:\
  - dir C:\
  # Only get certain submodules (not OpenSimAPI).
  - git submodule update --init --recursive -- opensim-models opensim-visualizer Gui/opensim/threejs
  
build_script:
  # Tweak installer files for the AppVeyor deployment.
  - ps: $env:commitHash = git describe --always # short commit hash or annotated tag, if one exists.
  - ps: $env:commitDate = git show -s --format=%cd --date=short HEAD
  - ps: $env:VERSION = "$env:commitHash"
  - ps: if (!($env.APPVEYOR_REPO_TAG)) { $env:VERSION = "$env:VERSION-$env:commitDate" }
  - ps: $env:VERSION
  - ps: (Get-Content $env:APPVEYOR_BUILD_FOLDER/Gui/opensim/installer_files/Windows/opensim.conf).replace('/dev', '/' + $env:VERSION) | Set-Content $env:APPVEYOR_BUILD_FOLDER/Gui/opensim/installer_files/Windows/opensim.conf
  - ps: (Get-Content $env:APPVEYOR_BUILD_FOLDER/Gui/opensim/nbproject/project.properties).replace('app.version=4.0.Beta', 'app.version=' + $env:VERSION) | Set-Content $env:APPVEYOR_BUILD_FOLDER/Gui/opensim/nbproject/project.properties
  - ps: mkdir ../build
  - cd ../build
  - cmake ../opensim-gui -G"Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=C:\opensim-core-VC141 -DANT_ARGS="-Dnbplatform.default.netbeans.dest.dir=C:/Program Files/NetBeans 8.2;-Dnbplatform.default.harness.dir=C:/Program Files/NetBeans 8.2/harness"
  - cmake --build . --target CopyOpenSimCore --config Release
  - cmake --build . --target CopyModels --config Release
  - cmake --build . --target PrepareInstaller --config Release
  - cmake --build . --target CopyJRE --config Release
  - cmake --build . --target CopyVisualizer --config Release
  #
  # TODO edit the .opensim folder name (in opensim.conf)
  
test_script:
  ## Run tests.
  - echo "No tests yet."
  # ant run

after_test:
  ## On master branch, create package for OpenSim.
  # Detect if we are on the master branch.
  - IF %APPVEYOR_REPO_BRANCH% EQU master IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER SET DISTR=TRUE
  # Create and upload package.
  - cd %APPVEYOR_BUILD_FOLDER%\Gui\opensim\dist\installer\
  - IF DEFINED DISTR "C:/Program Files (x86)/NSIS/makensis.exe" make_installer.nsi
  - IF DEFINED DISTR appveyor PushArtifact OpenSim-%VERSION%-win64.exe
  # - cd %APPVEYOR_BUILD_FOLDER%
  # - IF DEFINED DISTR 7z a C:\OpenSim-%VERSION%.zip %APPVEYOR_BUILD_FOLDER%\Gui\opensim\dist\installer\opensim\
  # - IF DEFINED DISTR appveyor PushArtifact C:\OpenSim-%VERSION%.zip
