name: opensim-application

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install opensim-core
      run: |
        (New-Object System.Net.WebClient).DownloadFile("https://prdownloads.sourceforge.net/myosin/github-actions/opensim-core/opensim-core-win.zip", "opensim-core-win.zip")
        7z x opensim-core-win.zip -oC:\\
        dir C:\\opensim-core

    - name: Checkout opensim-gui
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8


    - name: Install Netbeans
      # Make sure the NetBeans installer is not corrupted.
      run: |
        (New-Object System.Net.WebClient).DownloadFile("http://download.netbeans.org/netbeans/8.2/final/bundles/netbeans-8.2-javase-windows.exe", "netbeans-8.2-javase-windows.exe")
        $expectedHash = "7b0646306a7488e617837da1517a86c08b7cf6fbe4dd9d74e8a4564b5ffde004".ToUpper()
        $hashFromFile = Get-FileHash -Algorithm SHA256 -Path .\netbeans-8.2-javase-windows.exe
        if (($hashFromFile.Hash) -ne ($expectedHash)) { Write-Error "Hash doesn't match." }
        .\netbeans-8.2-javase-windows.exe --silent | Out-Null # This installer is gregarious.
        echo "::set-env name=ANT_HOME:C:\\Program Files\\NetBeans 8.2\\extide\\ant"
        
    - name: Update submodules
      run: git submodule update --init --recursive -- opensim-models opensim-visualizer Gui/opensim/threejs
      
    - name: Build GUI
      run: |
        mkdir build
        cd build
        cmake ../ -G"Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=C:\\opensim-core -DANT_ARGS="-Dnbplatform.default.netbeans.dest.dir=C:/Program Files/NetBeans 8.2;-Dnbplatform.default.harness.dir=C:/Program Files/NetBeans 8.2/harness"
        cmake --build . --target CopyOpenSimCore --config Release
        cmake --build . --target CopyModels --config Release
        cmake --build . --target PrepareInstaller --config Release
        cmake --build . --target CopyJRE --config Release
        cmake --build . --target CopyVisualizer --config Release
        # Read the value of the cache variable storing the GUI build version.
        $env:match = cmake -L . | Select-String -Pattern OPENSIMGUI_BUILD_VERSION
        $env:VERSION = $env:match.split('=')[1]
        $env:VERSION
        echo "::set-env name=VERSION:$env:VERSION"
        echo "::set-output name=version:$env:VERSION"

    - name: Build GUI installer
      run: |
        cd Gui/opensim/dist/installer
        makensis.exe make_installer.nsi
        mv OpenSim-${{ steps.build-gui.outputs.version}}.zip $env:GITHUB_WORKSPACE

    - name: Upload GUI installer
      uses: actions/upload-artifact@v1.0.0
      with:
        name: OpenSim-${{ steps.build-gui.outputs.version }}-Win64
        path: OpenSim-${{ steps.build-gui.outputs.version}}.zip



         
        
      
